# Exploratory Data Analysis

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("/home/linar/Desktop/ML/Clases/i302/Proyecto_Final/Mercado_Libre/Data/alquiler_2021_2022.csv")
df.head()

<ipython-input-2-320670e1a0af>:1: DtypeWarning: Columns (10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,32,35,37,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/home/linar/Desktop/ML/Clases/i302/Proyecto_Final/Mercado_Libre/Data/alquiler_2021_2022.csv")

,Unnamed: 0.1,Unnamed: 0,id_grid,MesListing,TIPOPROPIEDAD,STotalM2,SConstrM2,Dormitorios,Banos,Ambientes,...,CanchaTennis,AreaCine,ITE_ADD_CITY_NAME,ITE_ADD_STATE_NAME,ITE_ADD_NEIGHBORHOOD_NAME,ITE_TIPO_PROD,LONGITUDE,LATITUDE,precio_pesos_constantes,year
0,0,52,57127,2021-01-01,Departamento,53.0,53.0,2,1,3,...,0,0,Capital Federal,Capital Federal,Almagro,U,-58.418089,-34.613734,9496.990743,2021
1,1,57,60106,2021-01-01,Departamento,24.0,24.0,0,1,1,...,0,0,Capital Federal,Capital Federal,Retiro,U,-58.378565,-34.597957,5698.194446,2021
2,2,58,58737,2021-01-01,Departamento,72.0,60.0,2,2,3,...,0,0,Capital Federal,Capital Federal,Villa del Parque,N,-58.494256,-34.603808,20576.813275,2021
3,3,61,63383,2021-01-01,Departamento,130.0,125.0,2,2,3,...,0,0,Capital Federal,Capital Federal,Palermo,U,-58.406607,-34.579602,88638.580264,2021
4,4,68,57483,2021-01-01,Departamento,165.0,145.0,3,3,4,...,0,0,Capital Federal,Capital Federal,Puerto Madero,N,-58.359175,-34.612601,154383.081510,2021

In [3]:
df.describe()

,Unnamed: 0.1,Unnamed: 0,id_grid,STotalM2,SConstrM2,Dormitorios,Banos,Ambientes,Cocheras,PistaJogging,Lobby,LocalesComerciales,AreaParrillas,LONGITUDE,LATITUDE,precio_pesos_constantes,year
count,309695.000000,309695.000000,309695.000000,3.096730e+05,3.096730e+05,309695.000000,309695.000000,309695.000000,309695.000000,208924.0,208924.0,208924.0,281953.000000,309695.000000,309695.000000,3.096950e+05,309695.000000
mean,154847.000000,230702.501903,59838.465371,3.709395e+03,3.055057e+04,1.422196,1.335411,2.390391,0.404866,0.0,0.0,0.0,0.035467,-58.481552,-34.597902,8.067886e+04,2021.481774
std,89401.390146,132601.893062,14758.515132,9.182916e+05,7.985392e+06,1.197368,1.005176,1.404921,2.724517,0.0,0.0,0.0,0.184957,0.115300,0.081629,6.644863e+05,0.499669
min,0.000000,52.000000,124.000000,0.000000e+00,0.000000e+00,0.000000,-1.000000,0.000000,-4.000000,0.0,0.0,0.0,0.000000,-58.874595,-34.923504,4.264038e+01,2021.000000
25%,77423.500000,115556.000000,53528.000000,3.800000e+01,3.600000e+01,1.000000,1.000000,2.000000,0.000000,0.0,0.0,0.0,0.000000,-58.544341,-34.632240,6.568300e+03,2021.000000
50%,154847.000000,232422.000000,60082.000000,5.000000e+01,4.600000e+01,1.000000,1.000000,2.000000,0.000000,0.0,0.0,0.0,0.000000,-58.450050,-34.597882,9.169347e+03,2021.000000
75%,232270.500000,345393.000000,65662.000000,7.700000e+01,7.000000e+01,2.000000,1.000000,3.000000,1.000000,0.0,0.0,0.0,0.000000,-58.401673,-34.566600,1.883788e+04,2022.000000
max,309694.000000,465796.000000,97826.000000,3.321555e+08,2.287862e+09,99.000000,212.000000,212.000000,1000.000000,0.0,0.0,0.0,1.000000,-58.159577,-34.385571,3.518759e+07,2022.000000